BluetoothServer: BluetoothServer.cpp 
	g++ -o BluetoothServer BluetoothServer.cpp -lpthread -lbluetooth

BluetoothClient: BluetoothClient.cpp
	g++ -o BluetoothClient BluetoothClient.cpp -lpthread -lbluetooth
