BluetoothServer: BluetoothServer.cpp 
	g++ -o BluetoothServer BluetoothServer.cpp -lpthread -lbluetooth

bt:BinBotServer_v0.cpp
	g++ -o bt BinBotServer_v0.cpp -lpthread -lbluetooth

BluetoothClient: BluetoothClient.cpp
	g++ -o BluetoothClient BluetoothClient.cpp -lpthread -lbluetooth
